### ISSUE TITLE
2.1.0 Prerelease 6 crash

### ISSUE THREAD

**Issue by xzhuiz** [kingToolbox/WindTerm#119]
I have been using 2.1.0 Prerelease 3, which is super stable.
Last time I used 2.1.0 Prerelease 5, it crashed
This time 2.1.0 Prerelease 6 also crashed.
There is not much operation, just open a few tabs

core dump as follow
[70cbf851-f3b8-469e-81f1-1a30dcd3d52c.zip](https://github.com/kingToolbox/WindTerm/files/6780919/70cbf851-f3b8-469e-81f1-1a30dcd3d52c.zip)

**Comment by kingToolbox** [comment]
Wow, my preliminary analysis shows that there is indeed a null pointer access. I think this is at least one of the causes of instability. I will fix it, thank you very much!

**Comment by kingToolbox** [comment]
Hi, [WindTerm_2.1.0_Prerelease_7](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease) has finally been released and this issue should have been fixed. You can download and check it now. Thank you.

**Comment by xzhuiz** [comment]
@kingToolbox WindTerm_2.1.0_Prerelease_7 is better than WindTerm_2.1.0_Prerelease_6
but it's sad, it still crashed
There are two core dumps here, one clicks the window control in the upper right corner, and the other seems to open one tab

[e4cfb9af-2e92-43b3-9328-053def776191.zip](https://github.com/kingToolbox/WindTerm/files/6821408/e4cfb9af-2e92-43b3-9328-053def776191.zip)
[59727d5e-c8ee-4920-8ce7-e47022a17061.zip](https://github.com/kingToolbox/WindTerm/files/6821411/59727d5e-c8ee-4920-8ce7-e47022a17061.zip)

**Comment by kingToolbox** [comment]
Yes, unfortunately, the new analysis result still points to the previous error, and a null style pointer is used when drawing the text. It really makes me very frustrated. :disappointed:  I will continue to analyze and try to fix it again. Thank you very much.

**Comment by kingToolbox** [comment]
@xzhuiz
May I ask if you also use dual monitors? I read @Shellfishgene's [comment](https://github.com/kingToolbox/WindTerm/issues/110#issuecomment-880523598) and found that this crash is related to multiple screens. I didn't notice this before, because I don't have dual screens, so I have not been able to self-test this.

Maybe this is why I have been unable to reproduce the crash? Because the operation that caused the crash you mentioned is very simple, logically I should be able to reproduce it.

**Comment by xzhuiz** [comment]
yes,yes, i use a laptop with two external screens.
Come on

**Comment by kingToolbox** [comment]
I think this problem has finally been fixed, and I have released [WindTerm_2.1.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.1), please download and check it now. Thank you.

**Comment by kingToolbox** [comment]
Hello, does the new [WindTerm_2.1.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) still crash?

**Comment by kingToolbox** [comment]
The issue should have been fixed in the new [WindTerm_2.1.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) and self-test passed. Please reopen this issue if it is still valid. Thank you.

**Comment by xzhuiz** [comment]
It's been longer than pre 7, no crash
great

**Comment by kingToolbox** [comment]
Thank you for the good news. Welcome to continue submitting new issues and feature requests. :smile:
