### ISSUE TITLE
Caret style changes to default style

### ISSUE THREAD

**Issue by ydong08** [kingToolbox/WindTerm#517]
caret style is 'blinking line' in session settings as follow:
![line](https://user-images.githubusercontent.com/11952321/154016000-6a3dc284-b2ad-44be-bf0b-b01f043dff33.png)

However, caret style changes to default style 'block' at one point, without modifying any session settings , i really do not know which action invokes the change.
![block](https://user-images.githubusercontent.com/11952321/154016919-204f0186-b60a-49c4-97df-1b5dac0d4186.png)

**Comment by kingToolbox** [comment]
The caret style is also controlled by `Menubar - Session - Preference - Settings - Text - Caret`, which may conflict with `Session Settings - Window - Caret Style`. I will fix this in the next bugfix version `WindTerm_2.3.1`, which is expected to be released this week. Please stay tuned, thank you.

**Comment by ydong08** [comment]
After upgrading to WindTerm_2.3.1, this bug still occurs, fix may be not work.
following attachments are my configuration about caret style.
1. Preference - Settings:
![setting_line](https://user-images.githubusercontent.com/11952321/157567805-79d3c36d-cee5-47bd-b687-f03d03ac81ae.png)

2. Session Setting:
![session_setting_line](https://user-images.githubusercontent.com/11952321/157567891-b8b3d6e2-5501-46b1-8526-bce3afa62107.png)

3. Caret Style
![caret_block](https://user-images.githubusercontent.com/11952321/157568013-b25902c1-4f82-4a1d-a043-971ff4b5db3a.png)

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.4.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.4.0) has been released and this bug has been fixed. Please download and check it, thank you. 

In `WindTerm 2.4.0`, when returning from the alternative screen, such as `VI`, to the main screen, the main screen's cursor shape is now restored correctly. Note that sometimes the server command `WindTerm` to change the cursor shape, therefore it is difficult to keep the cursor shape unchanged at all times unless `WindTerm` does not respond to such control sequences.

**Comment by waittingsummer** [comment]
The latest 2.6.0 Release still doesn't seem to fix this issue 
![1](https://github.com/kingToolbox/WindTerm/assets/32017265/c4bcf2d0-13d5-445f-ae7f-bf378b8b357a)
![2](https://github.com/kingToolbox/WindTerm/assets/32017265/7298aa67-62b9-4cdf-ab1e-bc5cb5070c31)

**Comment by samrosenf** [comment]
I encountered the same issue in version 2.7.0 (on Windows).  
I was able to work around this problem by modifying the `user.sessions` file.  
Each one of my sessions had the same attribute of `"window.caretStyle" : "blinking line"`. This setting was different from the global settings I used.   
When replacing those lines with `"window.caretStyle" : "steady block"` it worked as expected.

So it's also a session settings. 
But editing the Caret under Text isn't available when editing a session, so **the user can't access it from the GUI.**
