### ISSUE TITLE
btop display incorrectly

### ISSUE THREAD

**Issue by thewangcj** [kingToolbox/WindTerm#583]
windterm: 2.3.1
[btop:](https://github.com/aristocratos/btop) : 1.2.4
os: Ubuntu 20.04.4 LTS

on windterm:
![uTools_1646905147878](https://user-images.githubusercontent.com/13983218/157634210-dc3b5e29-da84-4bed-b376-752d65af3e90.png)

on mobaxterm:
![uTools_1646905241029](https://user-images.githubusercontent.com/13983218/157634511-bf201c37-4e95-4204-aa52-9bf7cad05e5f.png)

**Comment by frayos** [comment]
Same here on 2.3.1
despite disabling
"Alternate line background color" + "use background color to erase screen"

**Comment by kingToolbox** [comment]
@thewangcj
Sorry for the late reply, maybe I missed this issue.

Since version `2.4.0` is already in preparation for release, I will investigate this issue and will fix it in the next version. Please stay tuned, thank you.

**Comment by kingToolbox** [comment]
I am happy to inform you that [WindTerm_2.4.0](https://github.com/kingToolbox/WindTerm/releases/tag/2.4.0) has been released and this bug has been fixed. Please download and check it, thank you.

**Comment by frayos** [comment]
Hello @kingToolbox 
Thank you for this !

Yet I still see the problem on 2.4.1 Linux, 
were you able to test on a specific platform maybe so I can try ? (I tested on btop 1.1.1 and latest 1.2.6)

**Comment by thewangcj** [comment]
> I am happy to inform you that [WindTerm_2.4.1](https://github.com/kingToolbox/WindTerm/releases/tag/2.4.0) has been released and this bug has been fixed. Please download and check it, thank you.
Thank you!
I've checked it, now it display correctly! Thanks again

**Comment by lesu1** [comment]
I see the same issue on Linux (CachyOS latest)
WindTerm 2.6.1
btop 1.4.0

**Comment by solaris111** [comment]
I can see the bug on WindTerm 2.7 windwos x64 release.

**Comment by MC-wither** [comment]
I see the same issue on Linux
WindTerm 2.7.0
btop 1.4.7
