### ISSUE TITLE
Kex error : no match for method encryption server→client

### ISSUE THREAD

**Issue by GuimLe** [kingToolbox/WindTerm#674]
Hello, great work everyone, really nice tool !
I am facing a connection problem and I don't understand what's happening, maybe someone could help.
I would like to connect to a server but I have this error : 
```
ssh_kex_select_methods: kex error : no match for method encryption server->client: server [chacha20-poly1305@openssh.com], client [aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,blowfish-cbc,3des-cbc]
```
I have checked Ciphers order for this connection because the problem seems to come from client and this is what I have got : 
```
chacha20-poly1305@openssh.com
aes128-gcm@openssh.com
aes256-gcm@openssh.com
aes192-ctr
aes256-ctr
...
```
I have manually changed the order of ciphers but the error is still giving me this feedback, so I don't understand my error.
Can anyone help me ?

**Comment by kingToolbox** [comment]
Sorry for the late reply. But I am happy to inform you that [WindTerm_2.4.1](https://github.com/kingToolbox/WindTerm/releases/tag/2.4.0) has been released and this bug has been fixed. Please download and check it, thank you.

**Comment by GuimLe** [comment]
Thank you for your answer, I've checked it but the problem is still present in 2.4.1.
Client cipher list/order is still ignored.
Is there another problem ?

**Comment by jeyriku** [comment]
Hi,

Same issue in version 2.5.0 on MacOS X 13.1 (Ventura).

`kex error : no match for method kex algos: server [curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256], client [diffie-hellman-group14-sha1]`

Thanks in advance for your help,

**Comment by yiqian987** [comment]
Same issue in version 2.6.1 on MacOS  Sequoia 15.1.1

**Comment by mwigakki** [comment]
encountered the same error. Is there any solutions?

**Comment by lightchxt** [comment]
> Same issue in version 2.6.1 on MacOS Sequoia 15.1.1

I have the same error

**Comment by mwigakki** [comment]
https://www.reddit.com/r/Remmina/comments/11gnxwh/error_when_attempting_to_ssh_to_older_centos_6/?rdt=58196 
This may help!
I followed the guide and modified `/etc/ssh/ssh_config` on my remote server. I added the encryption algorithm (aes256-gcm@openssh.com in my case) to the end of the `Ciphers` field in the configuration. This resolved the issue for me.
hope it helpful for you.

**Comment by th815** [comment]
I encountered this issue on macOS 15.1.1 as well.

kex error : no match for method encryption client->server: server [aes128-ctr,aes192-ctr,aes256-ctr,AEAD_AES_128_GCM,AEAD_AES_256_GCM,aes128-cbc,3des-cbc,aes256-cbc,des-cbc], client [aes256-gcm@openssh.com]
and
kex error : no match for method encryption client->server: server [aes128-ctr,aes192-ctr,aes256-ctr,AEAD_AES_128_GCM,AEAD_AES_256_GCM], client [aes256-gcm@openssh.com]


> Same issue in version 2.6.1 on MacOS Sequoia 15.1.1

**Comment by th815** [comment]
Same issue in version 2.6.1 on MacOS Sequoia 15.2

**Comment by Joker-zc** [comment]
> any chance it would help, I can confirm that this problem appears to new installs in Sequoia 15.1 For example I have another Mac which was with Mac OS 14, after upgrade to Sequoia 15.1 it still works. But another Mac which came with Sequoia 15.1 - I got same error

same to me, The initial system of my Mac was 15.1

**Comment by Stone-Crown** [comment]
Same issue in version 2.6.1 on MacOS Sequoia 15.3

**Comment by lvhuat** [comment]
hi guys,edit your profile like below:
```
cat /etc/ssh/crypto.conf
# Default algorithms favoring higher-performance FIPS algorithms
# in most cases.
#
# To configure these SSH algorithms, run the following command:
#
# sudo ln -fs crypto/apple.conf /etc/ssh/crypto.conf
#
#Ciphers ^aes128-gcm@openssh.com,aes256-gcm@openssh.com
Ciphers ^aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
KexAlgorithms ^ecdh-sha2-nistp256
MACs ^hmac-sha2-256-etm@openssh.com,hmac-sha2-256
```

@Stone-Crown @Joker-zc @ovinex @th815 @lightchxt

**Comment by lvhuat** [comment]
windterm only try ciphers in this file.

**Comment by yiqian987** [comment]
> hi guys,edit your profile like below:
> 
> ```
> cat /etc/ssh/crypto.conf
> # Default algorithms favoring higher-performance FIPS algorithms
> # in most cases.
> #
> # To configure these SSH algorithms, run the following command:
> #
> # sudo ln -fs crypto/apple.conf /etc/ssh/crypto.conf
> #
> #Ciphers ^aes128-gcm@openssh.com,aes256-gcm@openssh.com
> Ciphers ^aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
> KexAlgorithms ^ecdh-sha2-nistp256
> MACs ^hmac-sha2-256-etm@openssh.com,hmac-sha2-256
> ```
> 
> [@Stone-Crown](https://github.com/Stone-Crown) [@Joker-zc](https://github.com/Joker-zc) [@ovinex](https://github.com/ovinex) [@th815](https://github.com/th815) [@lightchxt](https://github.com/lightchxt)

It worked!

**Comment by Joker-zc** [comment]
thx! it works!!! @lvhuat @yiqian987 

> > hi guys,edit your profile like below:
> > ```
> > cat /etc/ssh/crypto.conf
> > # Default algorithms favoring higher-performance FIPS algorithms
> > # in most cases.
> > #
> > # To configure these SSH algorithms, run the following command:
> > #
> > # sudo ln -fs crypto/apple.conf /etc/ssh/crypto.conf
> > #
> > #Ciphers ^aes128-gcm@openssh.com,aes256-gcm@openssh.com
> > Ciphers ^aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
> > KexAlgorithms ^ecdh-sha2-nistp256
> > MACs ^hmac-sha2-256-etm@openssh.com,hmac-sha2-256
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [@Stone-Crown](https://github.com/Stone-Crown) [@Joker-zc](https://github.com/Joker-zc) [@ovinex](https://github.com/ovinex) [@th815](https://github.com/th815) [@lightchxt](https://github.com/lightchxt)
> 
> It worked!

**Comment by perrydzhu** [comment]
it worked, thanks

> windterm only try ciphers in this file.



> hi guys,edit your profile like below:
> 
> ```
> cat /etc/ssh/crypto.conf
> # Default algorithms favoring higher-performance FIPS algorithms
> # in most cases.
> #
> # To configure these SSH algorithms, run the following command:
> #
> # sudo ln -fs crypto/apple.conf /etc/ssh/crypto.conf
> #
> #Ciphers ^aes128-gcm@openssh.com,aes256-gcm@openssh.com
> Ciphers ^aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
> KexAlgorithms ^ecdh-sha2-nistp256
> MACs ^hmac-sha2-256-etm@openssh.com,hmac-sha2-256
> ```
> 
> [@Stone-Crown](https://github.com/Stone-Crown) [@Joker-zc](https://github.com/Joker-zc) [@ovinex](https://github.com/ovinex) [@th815](https://github.com/th815) [@lightchxt](https://github.com/lightchxt)

**Comment by BBS2013** [comment]
如果没有/etc/ssh/下没有crypto.conf，修改/etc/ssh/sshd_config 末尾追加也可以解决这个问题。

添加或修改 Ciphers 配置
按 G（大写）直接跳到文件末尾，然后按 o（小写字母）在末尾另起一行进入编辑模式。直接复制并粘贴以下这行配置：
Ciphers aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,aes128-cbc,3des-cbc

重启sshd:sudo systemctl restart sshd
