### ISSUE TITLE
Ctrl+X not working

### ISSUE THREAD

**Issue by karagi4** [kingToolbox/WindTerm#94]
Good afternoon! Maybe it's just fitch, but when I try to exit the nano editor by pressing Ctrl+X, the terminal displays a message like in the screenshot. And the exit from nano does not happen. In previous versions, this was not observed.

![image](https://user-images.githubusercontent.com/41114204/117418052-a6acf100-af23-11eb-9b4d-ce5fdf31d5ef.png)

**Comment by kingToolbox** [comment]
Hi, really happy to see you again. This is my mistake. In the latest version, I assigned the shortcut key `<Ctrl+X>{5}` to cancel the running lz/sz, this results in the `<Ctrl+X>` key being preferentially used to match `<Ctrl+X>{5}` instead of being sent to the remote server.

You can open the `WindTerm-install-path/global/wind.keymaps` and modify:
``` json
  { "keys": "<Ctrl+X>{5}",
    "modes": "remote",
    "script": "() => { window.activeText.cancelModemTransfering() }"
  },
```
to:
``` json
  { "keys": "<Ctrl+X>{5}",
    "modes": "remote",
    "when": "terminal.activeView().isModemTransfering()",
    "script": "() => { window.activeText.cancelModemTransfering() }"
  },
```
I think this can solve the problem, and I will provide a more complete solution in the next version.

**Comment by kingToolbox** [comment]
Hi, [WindTerm_2.1.0_Prerelease_3](https://github.com/kingToolbox/WindTerm/releases/tag/2.1) has just been released and this issue has been fixed. You can download and check it now. Thank you.

**Comment by kingToolbox** [comment]
Self-test passed [WindTerm_2.1.0_Prerelase_4](https://github.com/kingToolbox/WindTerm/releases/tag/2.1-prerelease), and this issue will be closed because no further activity occurs during the last month. Please reopen this issue if it is still valid. Thank you.

**Comment by tangruixun** [comment]
Still have this issue in 2.6.0, which makes `Emacs` unusable.
